language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.2
  - DJANGO=1.5.1
  - DJANGO=1.6.0
matrix:
  exclude:
  - python: "3.2"
    env: DJANGO=1.4.2
  - python: "3.3"
    env: DJANGO=1.4.2

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python runtests.py

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
